### ISSUE TITLE
Large Scale Inference & Cloud Scaling Session

### ISSUE THREAD

**Issue by wildintellect** [developmentseed/sat-ml-training#31]
@drewbo this session "Large Scale Inference, Cloud Scaling", lesson number 6, on Oct 8, which is the final lesson before office hours is up to you. 

@Geoyi mentioned discussing some topics with you and @lillythomas . A few things we thought about in scrum that might be good to include, which are not well covered elsewhere.

* Demo how to connect to a GCP instance as a backend for Colab - References[1](https://medium.com/@senthilnathangautham/colab-gcp-compute-how-to-link-them-together-98747e8d940e) [2](https://medium.com/@yufengg/how-to-upgrade-colab-with-more-compute-64d53a9b05dc) , participants need not do this since it would require setting up GCP accounts/IAM/etc.
* Enabling GPU (Lilly will briefly show how to enable in Colab as part of lesson 4) 
* Using COGs as a data source instead of single tifs on Google Drive. The Sentinel 2 for Africa that @vincentsarago mentioned is Requester Pays, so wasn't easy to work into an example. Not sure if there is a good GCS bucket with COGs that could be used or another source. @vincentsarago maybe a standard notebook you have from previous talks you've done could be used.

**Comment by vincentsarago** [comment]
>  The Sentinel 2 for Africa that @vincentsarago mentioned is Requester Pays, so wasn't easy to work into an example. 

I don't think it's in requester-pays (maybe it changed recently)

**Comment by wildintellect** [comment]
@vincentsarago provided a notebook on using STAC and COGs, put that in as a draft to start the material.
* You can see it online, will be added to homepage when it's ready https://devseed.com/sat-ml-training/Scaling
* [Code](https://github.com/developmentseed/sat-ml-training/blob/main/_notebooks/2020-10-08-Scaling.ipynb)
* TODO: testing in Colab - possibly simplify if it's too complicated.

@drewbo Add what you want to teach on Inference scaling.

**Comment by drewbo** [comment]
Added https://developmentseed.org/sat-ml-training/Earth-Engine-Inference

The workflow itself is functional but it contains one bug: the images generated from GEE are indices scaled from -1 to 1 and the training data is per-image, per-band scaled indices from 0-1. That latter normalization needs to be added to the `doPrediction` function for this to work properly. cc: @lillythomas
